apiServer:
  port: 8080
  publicHost: itenero-server-639636909074.us-central1.run.app
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: itenero-server-639636909074.us-central1.run.app
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: itenero-server-639636909074.us-central1.run.app
  publicPort: 443
  publicScheme: https


 # host: /cloudsql/itenero-app:us-central1:itenero-db #35.188.31.139


database:
  host: 34.133.230.247
  port: 5432
  name: itenero
  user: postgres
  requireSsl: false

redis:
  enabled: false

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: true
