name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.1.1'
      SERVERPOD_PASSWORD_database: 'AFQ9EK2n6N-pPE3ufkwfh4J7CppaOV0v'
      SERVERPOD_PASSWORD_redis: '2okP952IL8hkiYzQM46cRPR9in_efyFx'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: itenero_app_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: itenero_app_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: itenero_app_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: itenero_app_server
        run: serverpod generate

      - name: Run tests
        working-directory: itenero_app_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: itenero_app_server
        run: docker compose down -v
